# Generated by Django 3.2.3 on 2021-05-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='type first name', max_length=100)),
                ('last_name', models.CharField(help_text='type last name', max_length=100)),
                ('province', models.CharField(help_text='province like ON, AB', max_length=2)),
                ('dat_of_birth', models.DateField()),
                ('alt_first_name', models.CharField(help_text='alt first name', max_length=100)),
                ('alt_last_name', models.CharField(help_text='alt last name', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='type first name', max_length=100)),
                ('last_name', models.CharField(help_text='type last name', max_length=100)),
                ('province', models.CharField(help_text='province like ON, AB', max_length=2)),
                ('dat_of_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'STRONG'), (1, 'POSSIBLE'), (1, 'WEAK')], default=1)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_challenge_app.notice')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_challenge_app.record')),
            ],
        ),
    ]
