# Generated by Django 3.2.3 on 2021-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_challenge_app', '0002_match_notice_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='alt_first_name',
            field=models.CharField(blank=True, help_text='alt first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='alt_last_name',
            field=models.CharField(blank=True, help_text='alt last name', max_length=100),
        ),
    ]
