# Generated by Django 3.2.3 on 2021-05-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_challenge_app', '0005_auto_20210527_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'STRONG'), (2, 'POSSIBLE'), (3, 'WEAK')], default=1),
        ),
    ]
