# Generated by Django 3.2.3 on 2021-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_challenge_app', '0006_alter_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='dat_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='dat_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
